configuration:
  kb_url: <URL>
  uc_field: rules
  uc_regex: UC-\w+-\d+
  uc_kb_name_regex: UC-\w+-\d+-[\w\-_ ]*
  event_start_time: Start Time
  event_start_time_format: "%Y-%m-%d %H:%M:%S"
  event_id_field: Offense ID
  mail_responder_id: <id>
  mail_header: <header>
  mail_footer: <footer>
  mail_sender_name: <sender name>