name: package pip
on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 0 * * *'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - package-ecosystem: "pip"
      # Look for `build.gradle` in the `root` directory
      directory: "/"
      # Check for updates once weekly
      schedule:
        interval: "weekly"
        ignore:
        # Ignore updates to packages that start 'aws'
        # Wildcards match zero or more arbitrary characters
        - dependency-name: "flask*"